<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Event;
use App\Models\EventRegistration;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\Storage;

class SertifikatController extends Controller
{
    public function generate(Request $request)
    {
        $request->validate([
            'user_id' => 'required|exists:users,id',
            'event_id' => 'required|exists:events,id',
        ]);

        $registration = EventRegistration::where('user_id', $request->user_id)
            ->where('event_id', $request->event_id)
            ->where('status_kehadiran', 'hadir')
            ->first();

        if (!$registration) {
            return response()->json([
                'success' => false,
                'message' => 'User belum dinyatakan hadir pada event ini.'
            ], 403);
        }

        $user = User::find($request->user_id);
        $event = Event::find($request->event_id);

        $html = '
            <h1 style="text-align:center;">SERTIFIKAT</h1>
            <p style="text-align:center;">Diberikan kepada:</p>
            <h2 style="text-align:center;">' . $user->name . '</h2>
            <p style="text-align:center;">Sebagai peserta dalam acara:</p>
            <h3 style="text-align:center;">' . $event->nama . '</h3>
            <p style="text-align:center;">Pada tanggal: ' . $event->waktu_mulai . '</p>
        ';

        $pdf = Pdf::loadHTML($html);

        $fileName = 'sertifikat_' . $user->id . '_' . $event->id . '.pdf';
        $filePath = 'public/sertifikat/' . $fileName;

        Storage::put($filePath, $pdf->output());

        return response()->json([
            'success' => true,
            'message' => 'Sertifikat berhasil dibuat.',
            'file_url' => asset('storage/sertifikat/' . $fileName)
        ]);
    }

    public function generateByRegistrationId($registration_id)
    {
        $registration = EventRegistration::with(['user', 'event'])->find($registration_id);

        if (!$registration) {
            return response()->json([
                'success' => false,
                'message' => 'Data tidak ditemukan.'
            ], 404);
        }

        if ($registration->status_kehadiran !== 'hadir') {
            return response()->json([
                'success' => false,
                'message' => 'User belum dinyatakan hadir pada event ini.'
            ], 403);
        }

        $user = $registration->user;
        $event = $registration->event;

        // Data untuk barcode (bisa disesuaikan)
        $barcodeText = url('/api/verifikasi-sertifikat/' . $registration->id);
        $barcode = new \Milon\Barcode\DNS2D();
        $barcode->setStorPath(public_path('barcodes/')); 
        $barcodeImg = $barcode->getBarcodePNG($barcodeText, 'QRCODE');

        $html = '
    <html>
    <head>
        <style>
            body {
                font-family: "Times New Roman", serif;
                text-align: center;
                padding: 50px;
                border: 10px solid #4a90e2;
                position: relative;
            }

            h1 {
                font-size: 48px;
                margin-bottom: 0;
                color: #2c3e50;
            }

            h2 {
                font-size: 32px;
                margin: 10px 0;
                color: #34495e;
            }

            h3 {
                font-size: 24px;
                color: #2980b9;
                margin-top: 30px;
            }

            p {
                font-size: 18px;
                color: #555;
            }

            .bottom-border {
                position: absolute;
                bottom: 100px;
                left: 50px;
                right: 50px;
                height: 2px;
                background: linear-gradient(to right, #4a90e2, #2980b9, #4a90e2);
            }

            .footer {
                position: absolute;
                bottom: 30px;
                left: 0;
                right: 0;
                font-size: 14px;
                color: #888;
            }

            .barcode {
                margin-top: 40px;
            }
        </style>
    </head>
    <body>
        <h1>SERTIFIKAT</h1>
        <p>Diberikan kepada:</p>
        <h2>' . htmlspecialchars($user->name) . '</h2>
        <p>Sebagai peserta dalam acara:</p>
        <h3>' . htmlspecialchars($event->nama) . '</h3>
        <p>Pada tanggal: ' . date('d F Y', strtotime($event->waktu_mulai)) . '</p>

        <div class="bottom-border"></div>

        <div class="barcode">
            <img src="data:image/png;base64,' . $barcodeImg . '" width="120" />
        </div>

        <div class="footer">Generated by EO System</div>
    </body>
    </html>
    ';

        $pdf = \Barryvdh\DomPDF\Facade\Pdf::loadHTML($html);
        $pdf->setPaper('a4', 'landscape');

        $fileName = 'sertifikat_' . $user->id . '_' . $event->id . '.pdf';

        return $pdf->download($fileName);
    }

    public function verifikasiSertifikat($registration_id)
    {
        $registration = EventRegistration::with(['user', 'event'])->find($registration_id);

        if (!$registration) {
            return response('<h2 style="color:red;text-align:center;margin-top:50px;">Registrasi tidak ditemukan.</h2>', 404);
        }

        if ($registration->status_kehadiran !== 'hadir') {
            return response('<h2 style="color:red;text-align:center;margin-top:50px;">Sertifikat tidak valid karena user belum dinyatakan hadir.</h2>', 403);
        }

        $user = $registration->user;
        $event = $registration->event;

        $html = '
    <!DOCTYPE html>
    <html lang="id">
    <head>
        <meta charset="UTF-8">
        <title>Verifikasi Sertifikat</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f3f3f3;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
            }

            .card {
                background-color: #fff;
                padding: 40px;
                border-radius: 12px;
                box-shadow: 0 0 10px rgba(0,0,0,0.1);
                text-align: center;
                max-width: 600px;
                width: 100%;
            }

            .success {
                color: green;
                font-size: 24px;
                font-weight: bold;
            }

            .info {
                margin-top: 20px;
                text-align: left;
                font-size: 18px;
            }

            .info p {
                margin: 6px 0;
            }
        </style>
    </head>
    <body>
        <div class="card">
            <div class="success">✔ Sertifikat Terverifikasi</div>
            <div class="info">
                <p><strong>Nama:</strong> ' . htmlspecialchars($user->name) . '</p>
                <p><strong>Email:</strong> ' . htmlspecialchars($user->email) . '</p>
                <p><strong>Nama Event:</strong> ' . htmlspecialchars($event->nama) . '</p>
                <p><strong>Tanggal Event:</strong> ' . date('d F Y', strtotime($event->waktu_mulai)) . '</p>
                <p><strong>Status Kehadiran:</strong> Hadir</p>
            </div>
        </div>
    </body>
    </html>
    ';

        return response($html);
    }
}
